INSERT INTO romev3 (code, description) VALUES ("N4103", "Conduite de transport en commun sur route");
INSERT INTO romev3 (code, description) VALUES ("K2108", "Enseignement supérieur");
INSERT INTO romev3 (code, description) VALUES ("C1102", "Conseil clientèle en assurances");
INSERT INTO romev3 (code, description) VALUES ("J1305", "Conduite de véhicules sanitaires");
INSERT INTO romev3 (code, description) VALUES ("E1107", "Organisation d'évènementiel");
INSERT INTO romev3 (code, description) VALUES ("H1201", "Expertise technique couleur en industrie");
INSERT INTO romev3 (code, description) VALUES ("K1304", "Services domestiques");
INSERT INTO romev3 (code, description) VALUES ("K1703", "Direction opérationnelle de la défense");
INSERT INTO romev3 (code, description) VALUES ("H2204", "Encadrement des industries de l'ameublement et du bois");
INSERT INTO romev3 (code, description) VALUES ("E1102", "Ecriture d'ouvrages, de livres");
INSERT INTO romev3 (code, description) VALUES ("A1412", "Fabrication et affinage de fromages");
INSERT INTO romev3 (code, description) VALUES ("K1204", "Médiation sociale et facilitation de la vie en société");
INSERT INTO romev3 (code, description) VALUES ("M1706", "Promotion des ventes");
INSERT INTO romev3 (code, description) VALUES ("L1204", "Arts du cirque et arts visuels");
INSERT INTO romev3 (code, description) VALUES ("D1211", "Vente en articles de sport et loisirs");
INSERT INTO romev3 (code, description) VALUES ("A1407", "Élevage bovin ou équin");
INSERT INTO romev3 (code, description) VALUES ("E1205", "Réalisation de contenus multimédias");
INSERT INTO romev3 (code, description) VALUES ("F1703", "Maçonnerie");
INSERT INTO romev3 (code, description) VALUES ("I1303", "Installation et maintenance de distributeurs automatiques");
INSERT INTO romev3 (code, description) VALUES ("D1209", "Vente de végétaux");
INSERT INTO romev3 (code, description) VALUES ("G1101", "Accueil touristique");
INSERT INTO romev3 (code, description) VALUES ("K1303", "Assistance auprès d'enfants");
INSERT INTO romev3 (code, description) VALUES ("C1108", "Management de groupe et de service en assurances");
INSERT INTO romev3 (code, description) VALUES ("H1204", "Design industriel");
INSERT INTO romev3 (code, description) VALUES ("H1506", "Intervention technique qualité en mécanique et travail des métaux");
INSERT INTO romev3 (code, description) VALUES ("G1403", "Gestion de structure de loisirs ou d'hébergement touristique");
INSERT INTO romev3 (code, description) VALUES ("K2402", "Recherche en sciences de l'univers, de la matière et du vivant");
INSERT INTO romev3 (code, description) VALUES ("J1501", "Soins d'hygiène, de confort du patient");
INSERT INTO romev3 (code, description) VALUES ("M1802", "Expertise et support en systèmes d'information");
INSERT INTO romev3 (code, description) VALUES ("H1101", "Assistance et support technique client");
INSERT INTO romev3 (code, description) VALUES ("N2203", "Exploitation des pistes aéroportuaires");
INSERT INTO romev3 (code, description) VALUES ("L1503", "Décor et accessoires spectacle");
INSERT INTO romev3 (code, description) VALUES ("D1406", "Management en force de vente");
INSERT INTO romev3 (code, description) VALUES ("N4104", "Courses et livraisons express");
INSERT INTO romev3 (code, description) VALUES ("M1207", "Trésorerie et financement");
INSERT INTO romev3 (code, description) VALUES ("A1201", "Bûcheronnage et élagage");
INSERT INTO romev3 (code, description) VALUES ("I1502", "Intervention en milieu subaquatique");
INSERT INTO romev3 (code, description) VALUES ("J1507", "Soins infirmiers spécialisés en puériculture");
INSERT INTO romev3 (code, description) VALUES ("C1103", "Courtage en assurances");
INSERT INTO romev3 (code, description) VALUES ("K2110", "Formation en conduite de véhicules");
INSERT INTO romev3 (code, description) VALUES ("M1202", "Audit et contrôle comptables et financiers");
INSERT INTO romev3 (code, description) VALUES ("H1203", "Conception et dessin produits mécaniques");
INSERT INTO romev3 (code, description) VALUES ("K2203", "Management et inspection en propreté de locaux");
INSERT INTO romev3 (code, description) VALUES ("H2603", "Conduite d'installation automatisée de production électrique, électronique et microélectronique");
INSERT INTO romev3 (code, description) VALUES ("C1109", "Rédaction et gestion en assurances");
INSERT INTO romev3 (code, description) VALUES ("E1301", "Conduite de machines d'impression");
INSERT INTO romev3 (code, description) VALUES ("J1502", "Coordination de services médicaux ou paramédicaux");
INSERT INTO romev3 (code, description) VALUES ("H1301", "Inspection de conformité");
INSERT INTO romev3 (code, description) VALUES ("C1204", "Conception et expertise produits bancaires et financiers");
INSERT INTO romev3 (code, description) VALUES ("B1101", "Création en arts plastiques");
INSERT INTO romev3 (code, description) VALUES ("K1302", "Assistance auprès d'adultes");
INSERT INTO romev3 (code, description) VALUES ("G1206", "Personnel technique des jeux");
INSERT INTO romev3 (code, description) VALUES ("K2602", "Conseil en services funéraires");
INSERT INTO romev3 (code, description) VALUES ("H2504", "Encadrement d'équipe en industrie de transformation");
INSERT INTO romev3 (code, description) VALUES ("C1504", "Transaction immobilière");
INSERT INTO romev3 (code, description) VALUES ("E1104", "Conception de contenus multimédias");
INSERT INTO romev3 (code, description) VALUES ("E1402", "Élaboration de plan média");
INSERT INTO romev3 (code, description) VALUES ("D1213", "Vente en gros de matériel et équipement");
INSERT INTO romev3 (code, description) VALUES ("D1506", "Marchandisage");
INSERT INTO romev3 (code, description) VALUES ("M1502", "Développement des ressources humaines");
INSERT INTO romev3 (code, description) VALUES ("G1801", "Café, bar brasserie");
INSERT INTO romev3 (code, description) VALUES ("H1504", "Intervention technique en contrôle essai qualité en électricité et électronique");
INSERT INTO romev3 (code, description) VALUES ("K2601", "Conduite d'opérations funéraires");
INSERT INTO romev3 (code, description) VALUES ("H1210", "Intervention technique en études, recherche et");
INSERT INTO romev3 (code, description) VALUES ("C1105", "Études actuarielles en assurances");
INSERT INTO romev3 (code, description) VALUES ("D1206", "Réparation d'articles en cuir et matériaux souples");
INSERT INTO romev3 (code, description) VALUES ("H2601", "Bobinage électrique");
INSERT INTO romev3 (code, description) VALUES ("K1203", "Encadrement technique en insertion professionnelle");
INSERT INTO romev3 (code, description) VALUES ("J1405", "Optique - lunetterie");
INSERT INTO romev3 (code, description) VALUES ("B1802", "Réalisation d'articles en cuir et matériaux souples (hors vêtement)");
INSERT INTO romev3 (code, description) VALUES ("M1503", "Management des ressources humaines");
INSERT INTO romev3 (code, description) VALUES ("N2102", "Pilotage et navigation technique aérienne");
INSERT INTO romev3 (code, description) VALUES ("K1402", "Conseil en Santé Publique");
INSERT INTO romev3 (code, description) VALUES ("G1502", "Personnel polyvalent d'hôtellerie");
INSERT INTO romev3 (code, description) VALUES ("H2901", "Ajustement et montage de fabrication");
INSERT INTO romev3 (code, description) VALUES ("I1501", "Intervention en grande hauteur");
INSERT INTO romev3 (code, description) VALUES ("N1201", "Affrètement transport");
INSERT INTO romev3 (code, description) VALUES ("F1202", "Direction de chantier du BTP");
INSERT INTO romev3 (code, description) VALUES ("H2208", "Réalisation d'ouvrages décoratifs en bois");
INSERT INTO romev3 (code, description) VALUES ("I1309", "Maintenance électrique");
INSERT INTO romev3 (code, description) VALUES ("K1404", "Mise en oeuvre et pilotage de la politique des pouvoirs publics");
INSERT INTO romev3 (code, description) VALUES ("G1701", "Conciergerie en hôtellerie");
INSERT INTO romev3 (code, description) VALUES ("H1302", "Management et ingénierie Hygiène Sécurité Environnement -HSE- industriels");
INSERT INTO romev3 (code, description) VALUES ("H2906", "Conduite d'installation automatisée ou robotisée de fabrication mécanique");
INSERT INTO romev3 (code, description) VALUES ("F1601", "Application et décoration en plâtre, stuc et staff");
INSERT INTO romev3 (code, description) VALUES ("H2605", "Montage et câblage électronique");
INSERT INTO romev3 (code, description) VALUES ("B1301", "Décoration d'espaces de vente et d’exposition");
INSERT INTO romev3 (code, description) VALUES ("L1301", "Mise en scène de spectacles vivants");
INSERT INTO romev3 (code, description) VALUES ("B1805", "Stylisme");
INSERT INTO romev3 (code, description) VALUES ("E1202", "Production en laboratoire cinématographique");
INSERT INTO romev3 (code, description) VALUES ("M1702", "Analyse de tendance");
INSERT INTO romev3 (code, description) VALUES ("H3402", "Conduite de traitement par dépôt de surface");
INSERT INTO romev3 (code, description) VALUES ("H2203", "Conduite d'installation de production de panneaux bois");
INSERT INTO romev3 (code, description) VALUES ("N1301", "Conception et organisation de la chaîne logistique");
INSERT INTO romev3 (code, description) VALUES ("J1406", "Orthophonie");
INSERT INTO romev3 (code, description) VALUES ("N4302", "Contrôle des transports en commun");
INSERT INTO romev3 (code, description) VALUES ("J1306", "Imagerie médicale");
INSERT INTO romev3 (code, description) VALUES ("H2909", "Montage-assemblage mécanique");
INSERT INTO romev3 (code, description) VALUES ("I1401", "Maintenance informatique et bureautique");
INSERT INTO romev3 (code, description) VALUES ("M1606", "Saisie de données");
INSERT INTO romev3 (code, description) VALUES ("G1303", "Vente de voyages");
INSERT INTO romev3 (code, description) VALUES ("H3101", "Conduite d'équipement de fabrication de papier ou de carton");
INSERT INTO romev3 (code, description) VALUES ("C1110", "Souscription d'assurances");
INSERT INTO romev3 (code, description) VALUES ("N1202", "Gestion des opérations de circulation internationale des marchandises");
INSERT INTO romev3 (code, description) VALUES ("C1502", "Gestion locative immobilière");
INSERT INTO romev3 (code, description) VALUES ("A1503", "Toilettage des animaux");
INSERT INTO romev3 (code, description) VALUES ("H2505", "Encadrement d'équipe ou d'atelier en matériaux souples");
INSERT INTO romev3 (code, description) VALUES ("G1202", "Animation d'activités culturelles ou ludiques");
INSERT INTO romev3 (code, description) VALUES ("I1604", "Mécanique automobile et entretien de véhicules");
INSERT INTO romev3 (code, description) VALUES ("N1302", "Direction de site logistique");
INSERT INTO romev3 (code, description) VALUES ("G1602", "Personnel de cuisine");
INSERT INTO romev3 (code, description) VALUES ("K1904", "Magistrature");
INSERT INTO romev3 (code, description) VALUES ("C1101", "Conception - développement produits d'assurances");
INSERT INTO romev3 (code, description) VALUES ("I1402", "Réparation de biens électrodomestiques");
INSERT INTO romev3 (code, description) VALUES ("K2102", "Coordination pédagogique");
INSERT INTO romev3 (code, description) VALUES ("F1204", "Sécurité et protection santé du BTP");
INSERT INTO romev3 (code, description) VALUES ("L1501", "Coiffure et maquillage spectacle");
INSERT INTO romev3 (code, description) VALUES ("F1302", "Conduite d'engins de terrassement et de carrière");
INSERT INTO romev3 (code, description) VALUES ("G1501", "Personnel d'étage");
INSERT INTO romev3 (code, description) VALUES ("M1806", "Conseil et maîtrise d'ouvrage en systèmes d'information");
INSERT INTO romev3 (code, description) VALUES ("B1303", "Gravure - ciselure");
INSERT INTO romev3 (code, description) VALUES ("M1206", "Management de groupe ou de service comptable");
INSERT INTO romev3 (code, description) VALUES ("F1702", "Construction de routes et voies");
INSERT INTO romev3 (code, description) VALUES ("K2109", "Enseignement technique et professionnel");
INSERT INTO romev3 (code, description) VALUES ("M1201", "Analyse et ingénierie financière");
INSERT INTO romev3 (code, description) VALUES ("N1103", "Magasinage et préparation de commandes");
INSERT INTO romev3 (code, description) VALUES ("N4102", "Conduite de transport de particuliers");
INSERT INTO romev3 (code, description) VALUES ("A1205", "Sylviculture");
INSERT INTO romev3 (code, description) VALUES ("H2404", "Conduite de machine de production et transformation des fils");
INSERT INTO romev3 (code, description) VALUES ("D1405", "Conseil en information médicale");
INSERT INTO romev3 (code, description) VALUES ("L1502", "Costume et habillage spectacle");
INSERT INTO romev3 (code, description) VALUES ("H1207", "Rédaction technique");
INSERT INTO romev3 (code, description) VALUES ("K1102", "Aide aux bénéficiaires d'une mesure de protection juridique");
INSERT INTO romev3 (code, description) VALUES ("H2401", "Assemblage - montage d'articles en cuirs, peaux");
INSERT INTO romev3 (code, description) VALUES ("G1404", "Management d'établissement de restauration collective");
INSERT INTO romev3 (code, description) VALUES ("K1903", "Défense et conseil juridique");
INSERT INTO romev3 (code, description) VALUES ("B1302", "Décoration d'objets d'art et artisanaux");
INSERT INTO romev3 (code, description) VALUES ("L1303", "Promotion d'artistes et de spectacles");
INSERT INTO romev3 (code, description) VALUES ("C1104", "Direction d'exploitation en assurances");
INSERT INTO romev3 (code, description) VALUES ("G1802", "Management du service en restauration");
INSERT INTO romev3 (code, description) VALUES ("F1611", "Réalisation et restauration de façades");
INSERT INTO romev3 (code, description) VALUES ("M1707", "Stratégie commerciale");
INSERT INTO romev3 (code, description) VALUES ("F1102", "Conception - aménagement d'espaces intérieurs");
INSERT INTO romev3 (code, description) VALUES ("H2802", "Conduite d'installation de production de matériaux de construction");
INSERT INTO romev3 (code, description) VALUES ("N1102", "Déménagement");
INSERT INTO romev3 (code, description) VALUES ("G1402", "Management d'hôtel-restaurant");
INSERT INTO romev3 (code, description) VALUES ("N2201", "Personnel d'escale aéroportuaire");
INSERT INTO romev3 (code, description) VALUES ("E1204", "Projection cinéma");
INSERT INTO romev3 (code, description) VALUES ("I1103", "Supervision d'entretien et gestion de véhicules");
INSERT INTO romev3 (code, description) VALUES ("H2205", "Première transformation de bois d'oeuvre");
INSERT INTO romev3 (code, description) VALUES ("H2912", "Réglage d'équipement de production industrielle");
INSERT INTO romev3 (code, description) VALUES ("H2407", "Conduite de machine de transformation et de finition des cuirs et peaux");
INSERT INTO romev3 (code, description) VALUES ("K2111", "Formation professionnelle");
INSERT INTO romev3 (code, description) VALUES ("H2209", "Intervention technique en ameublement et bois");
INSERT INTO romev3 (code, description) VALUES ("M1804", "Études et développement de réseaux de télécoms");
INSERT INTO romev3 (code, description) VALUES ("H2905", "Conduite d'équipement de formage et découpage des matériaux");
INSERT INTO romev3 (code, description) VALUES ("J1506", "Soins infirmiers généralistes");
INSERT INTO romev3 (code, description) VALUES ("D1202", "Coiffure");
INSERT INTO romev3 (code, description) VALUES ("D1103", "Charcuterie - traiteur");
INSERT INTO romev3 (code, description) VALUES ("C1202", "Analyse de crédits et risques bancaires");
INSERT INTO romev3 (code, description) VALUES ("D1201", "Achat vente d'objets d'art, anciens ou d'occasion");
INSERT INTO romev3 (code, description) VALUES ("M1102", "Direction des achats");
INSERT INTO romev3 (code, description) VALUES ("K2502", "Management de sécurité privée");
INSERT INTO romev3 (code, description) VALUES ("J1307", "Préparation en pharmacie");
INSERT INTO romev3 (code, description) VALUES ("E1305", "Préparation et correction en édition et presse");
INSERT INTO romev3 (code, description) VALUES ("D1212", "Vente en décoration et équipement du foyer");
INSERT INTO romev3 (code, description) VALUES ("G1201", "Accompagnement de voyages, d'activités culturelles ou sportives");
INSERT INTO romev3 (code, description) VALUES ("I1607", "Réparation de cycles, motocycles et motoculteurs de loisirs");
INSERT INTO romev3 (code, description) VALUES ("N4401", "Circulation du réseau ferré");
INSERT INTO romev3 (code, description) VALUES ("K2107", "Enseignement général du second degré");
INSERT INTO romev3 (code, description) VALUES ("K1104", "Psychologie");
INSERT INTO romev3 (code, description) VALUES ("B1602", "Réalisation d'objets artistiques et fonctionnels en verre");
INSERT INTO romev3 (code, description) VALUES ("K1403", "Management de structure de santé, sociale ou pénitentiaire");
INSERT INTO romev3 (code, description) VALUES ("H1303", "Intervention technique en Hygiène Sécurité Environnement -HSE- industriel");
INSERT INTO romev3 (code, description) VALUES ("L1504", "Éclairage spectacle");
INSERT INTO romev3 (code, description) VALUES ("N4402", "Exploitation et manoeuvre des remontées mécaniques");
INSERT INTO romev3 (code, description) VALUES ("K2101", "Conseil en formation");
INSERT INTO romev3 (code, description) VALUES ("A1416", "Polyculture, élevage");
INSERT INTO romev3 (code, description) VALUES ("H3302", "Opérations manuelles d'assemblage, tri ou emballage");
INSERT INTO romev3 (code, description) VALUES ("H2408", "Conduite de machine d'impression textile");
INSERT INTO romev3 (code, description) VALUES ("K1602", "Gestion de patrimoine culturel");
INSERT INTO romev3 (code, description) VALUES ("K1802", "Développement local");
INSERT INTO romev3 (code, description) VALUES ("H1402", "Management et ingénierie méthodes et industrialisation");
INSERT INTO romev3 (code, description) VALUES ("B1401", "Réalisation d'objets en lianes, fibres et brins végétaux");
INSERT INTO romev3 (code, description) VALUES ("E1103", "Communication");
INSERT INTO romev3 (code, description) VALUES ("K2503", "Sécurité et surveillance privées");
INSERT INTO romev3 (code, description) VALUES ("A1401", "Aide agricole de production fruitière ou viticole");
INSERT INTO romev3 (code, description) VALUES ("N4204", "Intervention technique d'exploitation des transports routiers de personnes");
INSERT INTO romev3 (code, description) VALUES ("E1303", "Encadrement des industries graphiques");
INSERT INTO romev3 (code, description) VALUES ("H2914", "Réalisation et montage en tuyauterie");
INSERT INTO romev3 (code, description) VALUES ("N2205", "Direction d'escale et exploitation aéroportuaire");
INSERT INTO romev3 (code, description) VALUES ("I1304", "Installation et maintenance d'équipements industriels et d'exploitation");
INSERT INTO romev3 (code, description) VALUES ("N4101", "Conduite de transport de marchandises sur longue distance");
INSERT INTO romev3 (code, description) VALUES ("H1505", "Intervention technique en formulation et analyse sensorielle");
INSERT INTO romev3 (code, description) VALUES ("I1603", "Maintenance d'engins de chantier, levage, manutention et de machines agricoles");
INSERT INTO romev3 (code, description) VALUES ("I1306", "Installation et maintenance en froid, conditionnement d'air");
INSERT INTO romev3 (code, description) VALUES ("M1704", "Management relation clientèle");
INSERT INTO romev3 (code, description) VALUES ("I1301", "Installation et maintenance d'ascenseurs");
INSERT INTO romev3 (code, description) VALUES ("K2106", "Enseignement des écoles");
INSERT INTO romev3 (code, description) VALUES ("K2603", "Thanatopraxie");
INSERT INTO romev3 (code, description) VALUES ("D1208", "Soins esthétiques et corporels");
INSERT INTO romev3 (code, description) VALUES ("L1101", "Animation musicale et scénique");
INSERT INTO romev3 (code, description) VALUES ("H3303", "Préparation de matières et produits industriels (broyage, mélange, …)");
INSERT INTO romev3 (code, description) VALUES ("M1205", "Direction administrative et financière");
INSERT INTO romev3 (code, description) VALUES ("B1501", "Fabrication et réparation d'instruments de musique");
INSERT INTO romev3 (code, description) VALUES ("C1203", "Relation clients banque/finance");
INSERT INTO romev3 (code, description) VALUES ("H2301", "Conduite d'équipement de production chimique ou pharmaceutique");
INSERT INTO romev3 (code, description) VALUES ("N1303", "Intervention technique d'exploitation logistique");
INSERT INTO romev3 (code, description) VALUES ("D1207", "Retouches en habillement");
INSERT INTO romev3 (code, description) VALUES ("H2406", "Conduite de machine de traitement textile");
INSERT INTO romev3 (code, description) VALUES ("A1409", "Élevage de lapins et volailles");
INSERT INTO romev3 (code, description) VALUES ("A1502", "Podologie animale");
INSERT INTO romev3 (code, description) VALUES ("I1503", "Intervention en milieux et produits nocifs");
INSERT INTO romev3 (code, description) VALUES ("J1304", "Aide en puériculture");
INSERT INTO romev3 (code, description) VALUES ("F1105", "Études géologiques");
INSERT INTO romev3 (code, description) VALUES ("M1703", "Management et gestion de produit");
INSERT INTO romev3 (code, description) VALUES ("E1306", "Prépresse");
INSERT INTO romev3 (code, description) VALUES ("D1105", "Poissonnerie");
INSERT INTO romev3 (code, description) VALUES ("F1402", "Extraction solide");
INSERT INTO romev3 (code, description) VALUES ("H2502", "Management et ingénierie de production");
INSERT INTO romev3 (code, description) VALUES ("M1701", "Administration des ventes");
INSERT INTO romev3 (code, description) VALUES ("D1505", "Personnel de caisse");
INSERT INTO romev3 (code, description) VALUES ("I1602", "Maintenance d'aéronefs");
INSERT INTO romev3 (code, description) VALUES ("H1502", "Management et ingénierie qualité industrielle");
INSERT INTO romev3 (code, description) VALUES ("H2701", "Pilotage d'installation énergétique et pétrochimique");
INSERT INTO romev3 (code, description) VALUES ("F1701", "Construction en béton");
INSERT INTO romev3 (code, description) VALUES ("H2908", "Modelage de matériaux non métalliques");
INSERT INTO romev3 (code, description) VALUES ("H2602", "Câblage électrique et électromécanique");
INSERT INTO romev3 (code, description) VALUES ("J1101", "Médecine de prévention");
INSERT INTO romev3 (code, description) VALUES ("N1105", "Manutention manuelle de charges");
INSERT INTO romev3 (code, description) VALUES ("M1801", "Administration de systèmes d'information");
INSERT INTO romev3 (code, description) VALUES ("F1502", "Montage de structures métalliques");
INSERT INTO romev3 (code, description) VALUES ("H3403", "Conduite de traitement thermique");
INSERT INTO romev3 (code, description) VALUES ("K1205", "Information sociale");
INSERT INTO romev3 (code, description) VALUES ("D1204", "Location de véhicules ou de matériel de loisirs");
INSERT INTO romev3 (code, description) VALUES ("L1201", "Danse");
INSERT INTO romev3 (code, description) VALUES ("H2911", "Réalisation de structures métalliques");
INSERT INTO romev3 (code, description) VALUES ("G1604", "Fabrication de crêpes ou pizzas");
INSERT INTO romev3 (code, description) VALUES ("B1604", "Réparation - montage en systèmes horlogers");
INSERT INTO romev3 (code, description) VALUES ("J1103", "Médecine dentaire");
INSERT INTO romev3 (code, description) VALUES ("D1502", "Management/gestion de rayon produits alimentaires");
INSERT INTO romev3 (code, description) VALUES ("F1101", "Architecture du BTP");
INSERT INTO romev3 (code, description) VALUES ("A1413", "Fermentation de boissons alcoolisées");
INSERT INTO romev3 (code, description) VALUES ("K2401", "Recherche en sciences de l'homme et de la société");
INSERT INTO romev3 (code, description) VALUES ("H1501", "Direction de laboratoire d'analyse industrielle");
INSERT INTO romev3 (code, description) VALUES ("C1501", "Gérance immobilière");
INSERT INTO romev3 (code, description) VALUES ("H3401", "Conduite de traitement d'abrasion de surface");
INSERT INTO romev3 (code, description) VALUES ("M1810", "Production et exploitation de systèmes d'information");
INSERT INTO romev3 (code, description) VALUES ("D1503", "Management/gestion de rayon produits non alimentaires");
INSERT INTO romev3 (code, description) VALUES ("H2414", "Préparation et finition d'articles en cuir et matériaux souples");
INSERT INTO romev3 (code, description) VALUES ("M1603", "Distribution de documents");
INSERT INTO romev3 (code, description) VALUES ("D1107", "Vente en gros de produits frais");
INSERT INTO romev3 (code, description) VALUES ("M1404", "Management et gestion d'enquêtes");
INSERT INTO romev3 (code, description) VALUES ("J1504", "Soins infirmiers spécialisés en bloc opératoire");
INSERT INTO romev3 (code, description) VALUES ("H3202", "Réglage d'équipement de formage des plastiques et caoutchoucs");
INSERT INTO romev3 (code, description) VALUES ("H2907", "Conduite d'installation de production des métaux");
INSERT INTO romev3 (code, description) VALUES ("I1302", "Installation et maintenance d'automatismes");
INSERT INTO romev3 (code, description) VALUES ("D1401", "Assistanat commercial");
INSERT INTO romev3 (code, description) VALUES ("A1302", "Contrôle et diagnostic technique en agriculture");
INSERT INTO romev3 (code, description) VALUES ("K2201", "Blanchisserie industrielle");
INSERT INTO romev3 (code, description) VALUES ("M1403", "Études et prospectives socio-économiques");
INSERT INTO romev3 (code, description) VALUES ("D1101", "Boucherie");
INSERT INTO romev3 (code, description) VALUES ("J1505", "Soins infirmiers spécialisés en prévention");
INSERT INTO romev3 (code, description) VALUES ("K2112", "Orientation scolaire et professionnelle");
INSERT INTO romev3 (code, description) VALUES ("D1106", "Vente en alimentation");
INSERT INTO romev3 (code, description) VALUES ("A1405", "Arboriculture et viticulture");
INSERT INTO romev3 (code, description) VALUES ("K1305", "Intervention sociale et familiale");
INSERT INTO romev3 (code, description) VALUES ("M1402", "Conseil en organisation et management d'entreprise");
INSERT INTO romev3 (code, description) VALUES ("B1601", "Métallerie d'art");
INSERT INTO romev3 (code, description) VALUES ("H2101", "Abattage et découpe des viandes");
INSERT INTO romev3 (code, description) VALUES ("J1302", "Analyses médicales");
INSERT INTO romev3 (code, description) VALUES ("G1204", "Éducation en activités sportives");
INSERT INTO romev3 (code, description) VALUES ("I1308", "Maintenance d'installation de chauffage");
INSERT INTO romev3 (code, description) VALUES ("M1808", "Information géographique");
INSERT INTO romev3 (code, description) VALUES ("B1402", "Reliure et restauration de livres et archives");
INSERT INTO romev3 (code, description) VALUES ("E1203", "Production en laboratoire photographique");
INSERT INTO romev3 (code, description) VALUES ("N4201", "Direction d'exploitation des transports routiers de marchandises");
INSERT INTO romev3 (code, description) VALUES ("D1408", "Téléconseil et télévente");
INSERT INTO romev3 (code, description) VALUES ("B1603", "Réalisation d'ouvrages en bijouterie, joaillerie et orfèvrerie");
INSERT INTO romev3 (code, description) VALUES ("M1301", "Direction de grande entreprise ou d'établissement public");
INSERT INTO romev3 (code, description) VALUES ("N3102", "Equipage de la navigation maritime");
INSERT INTO romev3 (code, description) VALUES ("D1301", "Management de magasin de détail");
INSERT INTO romev3 (code, description) VALUES ("H3203", "Fabrication de pièces en matériaux composites");
INSERT INTO romev3 (code, description) VALUES ("A1303", "Ingénierie en agriculture et environnement naturel");
INSERT INTO romev3 (code, description) VALUES ("L1509", "Régie générale");
INSERT INTO romev3 (code, description) VALUES ("K2103", "Direction d'établissement et d'enseignement");
INSERT INTO romev3 (code, description) VALUES ("H1206", "Management et ingénierie études, recherche et développement industriel");
INSERT INTO romev3 (code, description) VALUES ("H2411", "Montage de prototype cuir et matériaux souples");
INSERT INTO romev3 (code, description) VALUES ("H2904", "Conduite d'équipement de déformation des métaux");
INSERT INTO romev3 (code, description) VALUES ("H2207", "Réalisation de meubles en bois");
INSERT INTO romev3 (code, description) VALUES ("D1407", "Relation technico-commerciale");
INSERT INTO romev3 (code, description) VALUES ("E1401", "Développement et promotion publicitaire");
INSERT INTO romev3 (code, description) VALUES ("K1706", "Sécurité publique");
INSERT INTO romev3 (code, description) VALUES ("H2503", "Pilotage d'unité élémentaire de production mécanique ou de travail des métaux");
INSERT INTO romev3 (code, description) VALUES ("H2403", "Conduite de machine de fabrication de produits textiles");
INSERT INTO romev3 (code, description) VALUES ("I1202", "Entretien et surveillance du tracé routier");
INSERT INTO romev3 (code, description) VALUES ("N4301", "Conduite sur rails");
INSERT INTO romev3 (code, description) VALUES ("K2303", "Nettoyage des espaces urbains");
INSERT INTO romev3 (code, description) VALUES ("K1503", "Contrôle et inspection des impôts");
INSERT INTO romev3 (code, description) VALUES ("A1415", "Equipage de la pêche");
INSERT INTO romev3 (code, description) VALUES ("M1604", "Assistanat de direction");
INSERT INTO romev3 (code, description) VALUES ("K1704", "Management de la sécurité publique");
INSERT INTO romev3 (code, description) VALUES ("F1107", "Mesures topographiques");
INSERT INTO romev3 (code, description) VALUES ("G1302", "Optimisation de produits touristiques");
INSERT INTO romev3 (code, description) VALUES ("H2206", "Réalisation de menuiserie bois et tonnellerie");
INSERT INTO romev3 (code, description) VALUES ("M1501", "Assistanat en ressources humaines");
INSERT INTO romev3 (code, description) VALUES ("H2410", "Mise en forme, repassage et finitions en industrie textile");
INSERT INTO romev3 (code, description) VALUES ("K2302", "Management et inspection en environnement urbain");
INSERT INTO romev3 (code, description) VALUES ("D1509", "Management de département en grande distribution");
INSERT INTO romev3 (code, description) VALUES ("K1502", "Contrôle et inspection des Affaires Sociales");
INSERT INTO romev3 (code, description) VALUES ("D1203", "Hydrothérapie");
INSERT INTO romev3 (code, description) VALUES ("D1507", "Mise en rayon libre-service");
INSERT INTO romev3 (code, description) VALUES ("F1401", "Extraction liquide et gazeuse");
INSERT INTO romev3 (code, description) VALUES ("J1403", "Ergothérapie");
INSERT INTO romev3 (code, description) VALUES ("L1505", "Image cinématographique et télévisuelle");
INSERT INTO romev3 (code, description) VALUES ("D1402", "Relation commerciale grands comptes et entreprises");
INSERT INTO romev3 (code, description) VALUES ("A1301", "Conseil et assistance technique en agriculture");
INSERT INTO romev3 (code, description) VALUES ("F1103", "Contrôle et diagnostic technique du bâtiment");
INSERT INTO romev3 (code, description) VALUES ("N2202", "Contrôle de la navigation aérienne");
INSERT INTO romev3 (code, description) VALUES ("G1703", "Réception en hôtellerie");
INSERT INTO romev3 (code, description) VALUES ("I1203", "Maintenance des bâtiments et des locaux");
INSERT INTO romev3 (code, description) VALUES ("F1106", "Ingénierie et études du BTP");
INSERT INTO romev3 (code, description) VALUES ("H2913", "Soudage manuel");
INSERT INTO romev3 (code, description) VALUES ("G1205", "Personnel d'attractions ou de structures de loisirs");
INSERT INTO romev3 (code, description) VALUES ("G1603", "Personnel polyvalent en restauration");
INSERT INTO romev3 (code, description) VALUES ("H3201", "Conduite d'équipement de formage des plastiques et caoutchoucs");
INSERT INTO romev3 (code, description) VALUES ("F1604", "Montage d'agencements");
INSERT INTO romev3 (code, description) VALUES ("G1605", "Plonge en restauration");
INSERT INTO romev3 (code, description) VALUES ("M1401", "Conduite d'enquêtes");
INSERT INTO romev3 (code, description) VALUES ("B1801", "Réalisation d'articles de chapellerie");
INSERT INTO romev3 (code, description) VALUES ("D1102", "Boulangerie - viennoiserie");
INSERT INTO romev3 (code, description) VALUES ("J1407", "Orthoptique");
INSERT INTO romev3 (code, description) VALUES ("K2104", "Éducation et surveillance au sein d'établissements d'enseignement");
INSERT INTO romev3 (code, description) VALUES ("H3301", "Conduite d'équipement de conditionnement");
INSERT INTO romev3 (code, description) VALUES ("J1102", "Médecine généraliste et spécialisée");
INSERT INTO romev3 (code, description) VALUES ("A1404", "Aquaculture");
INSERT INTO romev3 (code, description) VALUES ("F1501", "Montage de structures et de charpentes bois");
INSERT INTO romev3 (code, description) VALUES ("F1108", "Métré de la construction");
INSERT INTO romev3 (code, description) VALUES ("A1203", "Entretien des espaces verts");
INSERT INTO romev3 (code, description) VALUES ("F1603", "Installation d'équipements sanitaires et thermiques");
INSERT INTO romev3 (code, description) VALUES ("B1701", "Conservation et reconstitution d'espèces animales");
INSERT INTO romev3 (code, description) VALUES ("K1901", "Aide et médiation judiciaire");
INSERT INTO romev3 (code, description) VALUES ("I1305", "Installation et maintenance électronique");
INSERT INTO romev3 (code, description) VALUES ("F1613", "Travaux d'étanchéité et d'isolation");
INSERT INTO romev3 (code, description) VALUES ("H1404", "Intervention technique en méthodes et industrialisation");
INSERT INTO romev3 (code, description) VALUES ("A1504", "Santé animale");
INSERT INTO romev3 (code, description) VALUES ("H2405", "Conduite de machine de textiles nontissés");
INSERT INTO romev3 (code, description) VALUES ("A1408", "Élevage d'animaux sauvages ou de compagnie");
INSERT INTO romev3 (code, description) VALUES ("K2105", "Enseignement artistique");
INSERT INTO romev3 (code, description) VALUES ("M1805", "Études et développement informatique");
INSERT INTO romev3 (code, description) VALUES ("F1104", "Dessin BTP");
INSERT INTO romev3 (code, description) VALUES ("B1804", "Réalisation d'ouvrages d'art en fils");
INSERT INTO romev3 (code, description) VALUES ("K1505", "Protection des consommateurs et contrôle des échanges commerciaux");
INSERT INTO romev3 (code, description) VALUES ("H2903", "Conduite d'équipement d'usinage");
INSERT INTO romev3 (code, description) VALUES ("N4403", "Manoeuvre du réseau ferré");
INSERT INTO romev3 (code, description) VALUES ("H2910", "Moulage sable");
INSERT INTO romev3 (code, description) VALUES ("L1506", "Machinerie spectacle");
INSERT INTO romev3 (code, description) VALUES ("L1401", "Sportif professionnel");
INSERT INTO romev3 (code, description) VALUES ("C1303", "Gestion de portefeuilles sur les marchés financiers");
INSERT INTO romev3 (code, description) VALUES ("M1605", "Assistanat technique et administratif");
INSERT INTO romev3 (code, description) VALUES ("L1103", "Présentation de spectacles ou d'émissions");
INSERT INTO romev3 (code, description) VALUES ("M1609", "Secrétariat et assistanat médical ou médico-social");
INSERT INTO romev3 (code, description) VALUES ("K1405", "Représentation de l'Etat sur le territoire national ou international");
INSERT INTO romev3 (code, description) VALUES ("H2803", "Façonnage et émaillage en industrie céramique");
INSERT INTO romev3 (code, description) VALUES ("C1107", "Indemnisations en assurances");
INSERT INTO romev3 (code, description) VALUES ("F1203", "Direction et ingénierie d'exploitation de gisements et de carrières");
INSERT INTO romev3 (code, description) VALUES ("M1807", "Exploitation de systèmes de communication et de commandement");
INSERT INTO romev3 (code, description) VALUES ("N3202", "Exploitation du transport fluvial");
INSERT INTO romev3 (code, description) VALUES ("N3101", "Encadrement de la navigation maritime");
INSERT INTO romev3 (code, description) VALUES ("I1101", "Direction et ingénierie en entretien infrastructure et bâti");
INSERT INTO romev3 (code, description) VALUES ("E1101", "Animation de site multimédia");
INSERT INTO romev3 (code, description) VALUES ("J1408", "Ostéopathie et chiropraxie");
INSERT INTO romev3 (code, description) VALUES ("F1201", "Conduite de travaux du BTP");
INSERT INTO romev3 (code, description) VALUES ("N2204", "Préparation des vols");
INSERT INTO romev3 (code, description) VALUES ("H2604", "Montage de produits électriques et électroniques");
INSERT INTO romev3 (code, description) VALUES ("C1503", "Management de projet immobilier");
INSERT INTO romev3 (code, description) VALUES ("A1101", "Conduite d'engins agricoles et forestiers");
INSERT INTO romev3 (code, description) VALUES ("A1406", "Encadrement équipage de la pêche");
INSERT INTO romev3 (code, description) VALUES ("J1412", "Rééducation en psychomotricité");
INSERT INTO romev3 (code, description) VALUES ("I1310", "Maintenance mécanique industrielle");
INSERT INTO romev3 (code, description) VALUES ("F1609", "Pose de revêtements souples");
INSERT INTO romev3 (code, description) VALUES ("C1302", "Gestion back et middle-office marchés financiers");
INSERT INTO romev3 (code, description) VALUES ("H2412", "Patronnage - gradation");
INSERT INTO romev3 (code, description) VALUES ("C1301", "Front office marchés financiers");
INSERT INTO romev3 (code, description) VALUES ("D1205", "Nettoyage d'articles textiles ou cuirs");
INSERT INTO romev3 (code, description) VALUES ("K1207", "Intervention socioéducative");
INSERT INTO romev3 (code, description) VALUES ("A1202", "Entretien des espaces naturels");
INSERT INTO romev3 (code, description) VALUES ("H2801", "Conduite d'équipement de transformation du verre");
INSERT INTO romev3 (code, description) VALUES ("M1101", "Achats");
INSERT INTO romev3 (code, description) VALUES ("H2402", "Assemblage - montage de vêtements et produits textiles");
INSERT INTO romev3 (code, description) VALUES ("G1301", "Conception de produits touristiques");
INSERT INTO romev3 (code, description) VALUES ("F1705", "Pose de canalisations");
INSERT INTO romev3 (code, description) VALUES ("G1102", "Promotion du tourisme local");
INSERT INTO romev3 (code, description) VALUES ("D1501", "Animation de vente");
INSERT INTO romev3 (code, description) VALUES ("K2305", "Salubrité et traitement de nuisibles");
INSERT INTO romev3 (code, description) VALUES ("D1508", "Encadrement du personnel de caisses");
INSERT INTO romev3 (code, description) VALUES ("J1201", "Biologie médicale");
INSERT INTO romev3 (code, description) VALUES ("H1401", "Management et ingénierie gestion industrielle et logistique");
INSERT INTO romev3 (code, description) VALUES ("E1307", "Reprographie");
INSERT INTO romev3 (code, description) VALUES ("E1108", "Traduction, interprétariat");
INSERT INTO romev3 (code, description) VALUES ("A1414", "Horticulture et maraîchage");
INSERT INTO romev3 (code, description) VALUES ("F1704", "Préparation du gros oeuvre et des travaux publics");
INSERT INTO romev3 (code, description) VALUES ("K1401Conception", "et pilotage de la politique des pouvoirs publics");
INSERT INTO romev3 (code, description) VALUES ("F1605", "Montage de réseaux électriques et télécoms");
INSERT INTO romev3 (code, description) VALUES ("M1204", "Contrôle de gestion");
INSERT INTO romev3 (code, description) VALUES ("K1601", "Gestion de l'information et de la documentation");
INSERT INTO romev3 (code, description) VALUES ("H2415", "Contrôle en industrie du cuir et du textile");
INSERT INTO romev3 (code, description) VALUES ("K1701", "Personnel de la Défense");
INSERT INTO romev3 (code, description) VALUES ("J1402", "Diététique");
INSERT INTO romev3 (code, description) VALUES ("H1503", "Intervention technique en laboratoire d'analyse industrielle");
INSERT INTO romev3 (code, description) VALUES ("K2204", "Nettoyage de locaux");
INSERT INTO romev3 (code, description) VALUES ("M1601", "Accueil et renseignements");
INSERT INTO romev3 (code, description) VALUES ("C1401", "Gestion en banque et assurance");
INSERT INTO romev3 (code, description) VALUES ("J1303", "Assistance médico-technique");
INSERT INTO romev3 (code, description) VALUES ("H1208", "Intervention technique en études et conception en");
INSERT INTO romev3 (code, description) VALUES ("H2102", "Conduite d'équipement de production alimentaire");
INSERT INTO romev3 (code, description) VALUES ("H2201", "Assemblage d'ouvrages en bois");
INSERT INTO romev3 (code, description) VALUES ("G1203", "Animation de loisirs auprès d'enfants ou d'adolescents");
INSERT INTO romev3 (code, description) VALUES ("N4202", "Direction d'exploitation des transports routiers de personnes");
INSERT INTO romev3 (code, description) VALUES ("F1503", "Réalisation - installation d'ossatures bois");
INSERT INTO romev3 (code, description) VALUES ("K1301", "Accompagnement médicosocial");
INSERT INTO romev3 (code, description) VALUES ("K1201", "Action sociale");
INSERT INTO romev3 (code, description) VALUES ("F1301", "Conduite de grue");
INSERT INTO romev3 (code, description) VALUES ("K1101", "Accompagnement et médiation familiale");
INSERT INTO romev3 (code, description) VALUES ("A1402", "Aide agricole de production légumière ou végétale");
INSERT INTO romev3 (code, description) VALUES ("H2902", "Chaudronnerie - tôlerie");
INSERT INTO romev3 (code, description) VALUES ("D1210", "Vente en animalerie");
INSERT INTO romev3 (code, description) VALUES ("I1606", "Réparation de carrosserie");
INSERT INTO romev3 (code, description) VALUES ("N3103", "Navigation fluviale");
INSERT INTO romev3 (code, description) VALUES ("L1304", "Réalisation cinématographique et audiovisuelle");
INSERT INTO romev3 (code, description) VALUES ("G1702", "Personnel du hall");
INSERT INTO romev3 (code, description) VALUES ("H1202", "Conception et dessin de produits électriques et électroniques");
INSERT INTO romev3 (code, description) VALUES ("M1803", "Direction des systèmes d'information");
INSERT INTO romev3 (code, description) VALUES ("A1411", "Élevage porcin");
INSERT INTO romev3 (code, description) VALUES ("H1209", "Intervention technique en études et développement électronique");
INSERT INTO romev3 (code, description) VALUES ("F1706", "Préfabrication en béton industriel");
INSERT INTO romev3 (code, description) VALUES ("K2306", "Supervision d'exploitation éco-industrielle");
INSERT INTO romev3 (code, description) VALUES ("N1104", "Manoeuvre et conduite d'engins lourds de manutention");
INSERT INTO romev3 (code, description) VALUES ("H3102", "Conduite d'installation de pâte à papier");
INSERT INTO romev3 (code, description) VALUES ("C1201", "Accueil et services bancaires");
INSERT INTO romev3 (code, description) VALUES ("H1403", "Intervention technique en gestion industrielle et logistique");
INSERT INTO romev3 (code, description) VALUES ("G1803", "Service en restauration");
INSERT INTO romev3 (code, description) VALUES ("K2301", "Distribution et assainissement d'eau");
INSERT INTO romev3 (code, description) VALUES ("B1201", "Réalisation d'objets décoratifs et utilitaires en céramique et matériaux de synthèse");
INSERT INTO romev3 (code, description) VALUES ("D1403", "Relation commerciale auprès de particuliers");
INSERT INTO romev3 (code, description) VALUES ("F1602", "Électricité bâtiment");
INSERT INTO romev3 (code, description) VALUES ("J1202", "Pharmacie");
INSERT INTO romev3 (code, description) VALUES ("K2304", "Revalorisation de produits industriels");
INSERT INTO romev3 (code, description) VALUES ("H2804", "Pilotage de centrale à béton prêt à l'emploi, ciment, enrobés et granulats");
INSERT INTO romev3 (code, description) VALUES ("M1705", "Marketing");
INSERT INTO romev3 (code, description) VALUES ("N4203", "Intervention technique d'exploitation des transports routiers de marchandises");
INSERT INTO romev3 (code, description) VALUES ("F1608", "Pose de revêtements rigides");
INSERT INTO romev3 (code, description) VALUES ("A1501", "Aide aux soins animaux");
INSERT INTO romev3 (code, description) VALUES ("C1106", "Expertise risques en assurances");
INSERT INTO romev3 (code, description) VALUES ("K1707", "Surveillance municipale");
INSERT INTO romev3 (code, description) VALUES ("I1201", "Entretien d'affichage et mobilier urbain");
INSERT INTO romev3 (code, description) VALUES ("H2501", "Encadrement de production de matériel électrique et électronique");
INSERT INTO romev3 (code, description) VALUES ("L1508", "Prise de son et sonorisation");
INSERT INTO romev3 (code, description) VALUES ("N3203", "Manutention portuaire");
INSERT INTO romev3 (code, description) VALUES ("J1410", "Prothèses dentaires");
INSERT INTO romev3 (code, description) VALUES ("J1301", "Personnel polyvalent des services hospitaliers");
INSERT INTO romev3 (code, description) VALUES ("L1302", "Production et administration spectacle, cinéma et audiovisuel");
INSERT INTO romev3 (code, description) VALUES ("G1503", "Management du personnel d'étage");
INSERT INTO romev3 (code, description) VALUES ("A1403", "Aide d'élevage agricole et aquacole");
INSERT INTO romev3 (code, description) VALUES ("A1204", "Protection du patrimoine naturel");
INSERT INTO romev3 (code, description) VALUES ("C1205", "Conseil en gestion de patrimoine financier");
INSERT INTO romev3 (code, description) VALUES ("N4105", "Conduite et livraison par tournées sur courte distance");
INSERT INTO romev3 (code, description) VALUES ("G1601", "Management du personnel de cuisine");
INSERT INTO romev3 (code, description) VALUES ("J1503", "Soins infirmiers spécialisés en anesthésie");
INSERT INTO romev3 (code, description) VALUES ("K1103", "Développement personnel et bien-être de la personne");
INSERT INTO romev3 (code, description) VALUES ("E1201", "Photographie");
INSERT INTO romev3 (code, description) VALUES ("H2805", "Pilotage d'installation de production verrière");
INSERT INTO romev3 (code, description) VALUES ("K1702", "Direction de la sécurité civile et des secours");
INSERT INTO romev3 (code, description) VALUES ("M1302", "Direction de petite ou moyenne entreprise");
INSERT INTO romev3 (code, description) VALUES ("D1104", "Pâtisserie, confiserie, chocolaterie et glacerie");
INSERT INTO romev3 (code, description) VALUES ("D1214", "Vente en habillement et accessoires de la personne");
INSERT INTO romev3 (code, description) VALUES ("G1804", "Sommellerie");
INSERT INTO romev3 (code, description) VALUES ("N1101", "Conduite d'engins de déplacement des charges");
INSERT INTO romev3 (code, description) VALUES ("E1106", "Journalisme et information média");
INSERT INTO romev3 (code, description) VALUES ("L1203", "Art dramatique");
INSERT INTO romev3 (code, description) VALUES ("F1610", "Pose et restauration de couvertures");
INSERT INTO romev3 (code, description) VALUES ("G1401", "Assistance de direction d'hôtel-restaurant");
INSERT INTO romev3 (code, description) VALUES ("E1302", "Conduite de machines de façonnage routage");
INSERT INTO romev3 (code, description) VALUES ("B1806", "Tapisserie - décoration en ameublement");
INSERT INTO romev3 (code, description) VALUES ("F1607", "Pose de fermetures menuisées");
INSERT INTO romev3 (code, description) VALUES ("M1203", "Comptabilité");
INSERT INTO romev3 (code, description) VALUES ("L1102", "Mannequinat et pose artistique");
INSERT INTO romev3 (code, description) VALUES ("K1705", "Sécurité civile et secours");
INSERT INTO romev3 (code, description) VALUES ("I1307", "Installation et maintenance télécoms et courants faibles");
INSERT INTO romev3 (code, description) VALUES ("K1206", "Intervention socioculturelle");
INSERT INTO romev3 (code, description) VALUES ("I1601", "Installation et maintenance en nautisme");
INSERT INTO romev3 (code, description) VALUES ("M1607", "Secrétariat");
INSERT INTO romev3 (code, description) VALUES ("J1104", "Suivi de la grossesse et de l'accouchement");
INSERT INTO romev3 (code, description) VALUES ("D1504", "Direction de magasin de grande distribution");
INSERT INTO romev3 (code, description) VALUES ("D1404", "Relation commerciale en vente de véhicules");
INSERT INTO romev3 (code, description) VALUES ("A1417", "Saliculture");
INSERT INTO romev3 (code, description) VALUES ("J1409", "Pédicurie et podologie");
INSERT INTO romev3 (code, description) VALUES ("K1202", "Éducation de jeunes enfants");
INSERT INTO romev3 (code, description) VALUES ("H2413", "Préparation de fils, montage de métiers textiles");
INSERT INTO romev3 (code, description) VALUES ("H2202", "Conduite d'équipement de fabrication de l'ameublement et du bois");
INSERT INTO romev3 (code, description) VALUES ("H3404", "Peinture industrielle");
INSERT INTO romev3 (code, description) VALUES ("K1902", "Collaboration juridique");
INSERT INTO romev3 (code, description) VALUES ("M1608", "Secrétariat comptable");
INSERT INTO romev3 (code, description) VALUES ("E1304", "Façonnage et routage");
INSERT INTO romev3 (code, description) VALUES ("A1410", "Élevage ovin ou caprin");
INSERT INTO romev3 (code, description) VALUES ("F1612", "Taille et décoration de pierres");
INSERT INTO romev3 (code, description) VALUES ("M1602", "Opérations administratives");
INSERT INTO romev3 (code, description) VALUES ("H2409", "Coupe cuir, textile et matériaux souples");
INSERT INTO romev3 (code, description) VALUES ("K1501", "Application des règles financières publiques");
INSERT INTO romev3 (code, description) VALUES ("H1102", "Management et ingénierie d'affaires");
INSERT INTO romev3 (code, description) VALUES ("E1105", "Coordination d'édition");
INSERT INTO romev3 (code, description) VALUES ("H1205", "Études - modèles en industrie des matériaux souples");
INSERT INTO romev3 (code, description) VALUES ("N3201", "Exploitation des opérations portuaires et du transport maritime");
INSERT INTO romev3 (code, description) VALUES ("L1507", "Montage audiovisuel et post-production");
INSERT INTO romev3 (code, description) VALUES ("I1102", "Management et ingénierie de maintenance industrielle");
INSERT INTO romev3 (code, description) VALUES ("C1207", "Management en exploitation bancaire");
INSERT INTO romev3 (code, description) VALUES ("K2202", "Lavage de vitres");
INSERT INTO romev3 (code, description) VALUES ("B1803", "Réalisation de vêtements sur mesure ou en petite série");
INSERT INTO romev3 (code, description) VALUES ("J1401", "Audioprothèses");
INSERT INTO romev3 (code, description) VALUES ("E1308", "Intervention technique en industrie graphique");
INSERT INTO romev3 (code, description) VALUES ("I1605", "Mécanique de marine");
INSERT INTO romev3 (code, description) VALUES ("J1411", "Prothèses et orthèses");
INSERT INTO romev3 (code, description) VALUES ("N2101", "Navigation commerciale aérienne");
INSERT INTO romev3 (code, description) VALUES ("M1809", "Information météorologique");
INSERT INTO romev3 (code, description) VALUES ("L1202", "Musique et chant");
INSERT INTO romev3 (code, description) VALUES ("F1606", "Peinture en bâtiment");
INSERT INTO romev3 (code, description) VALUES ("K1801", "Conseil en emploi et insertion socioprofessionnelle");
INSERT INTO romev3 (code, description) VALUES ("K2501", "Gardiennage de locaux");
INSERT INTO romev3 (code, description) VALUES ("J1404", "Kinésithérapie");
INSERT INTO romev3 (code, description) VALUES ("C1206", "Gestion de clientèle bancaire");
INSERT INTO romev3 (code, description) VALUES ("K1504", "Contrôle et inspection du Trésor Public");